spring.application.name=spring-ai-travel-agent
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:./data/traveldb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.ai.chat.memory.repository.jdbc.initialize-schema=never

# Keeps existing table structure intact and appends schema updates on restart
#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema.sql

#OAuth disbled temporarly
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/company-realm

# OpenWeather API Configuration
openweather.api.key=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
openweather.api.url=https://api.openweathermap.org/data/2.5

# Enable Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus,traces

# Set tracing sample rate to 100% for development
management.tracing.sampling.probability=1.0

# OpenTelemetry OTLP Exporter Endpoint (e.g., Jaeger, Zipkin, or OTel Collector)
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.tracing.transport=http

# Spring AI Observation metrics logging
spring.ai.chat.observations.include-prompt=true

## Qdrant vector store
#spring.ai.vectorstore.qdrant.initialize-schema=true
#spring.ai.vectorstore.qdrant.host=localhost
#spring.ai.vectorstore.qdrant.port=6334
#spring.ai.vectorstore.qdrant.collection-name=company
#app.rag.load.random=false
#app.rag.load.hr=false
